version: "3.1"

services:
  flasky:
    build: ./flasky/
    ports:
      - "5000:5000"
    volumes:
      - "./flasky:/flasky"
    environment:
      ENV: "DEV"
      SECRET_KEY_FILE: /run/secrets/flasky-secret
      MAIL_USERNAME_FILE: /run/secrets/flasky-mail-username
      MAIL_PASSWORD_FILE: /run/secrets/flasky-mail-password
      ADMIN_EMAIL_FILE: /run/secrets/flasky-admin
      ADMIN_PASSWORD_FILE: /run/secrets/flasky-admin-password
    secrets:
      - flasky-secret
      - flasky-mail-username
      - flasky-mail-password
      - flasky-admin
      - flasky-admin-password

secrets:
  flasky-secret:
    file: credentials/flasky-secret.txt
  flasky-mail-username:
    file: credentials/flasky-mail-username.txt
  flasky-mail-password:
    file: credentials/flasky-mail-password.txt
  flasky-admin:
    file: credentials/flasky-admin.txt
  flasky-admin-password:
    file: credentials/flasky-admin-password.txt
